### ISSUE TITLE
Selenium Webdriver wait.py always throws TimeOutException

### ISSUE THREAD

**Issue by gordon-sk** [spatel4140/bing-rewards#12]
Attempting to use the script on a mac -- I'm using Python 3, with the exact library requirements listed. Unfortunately I always hit a timeoutexception no matter which search type I choose. My output is below:

python3 BingRewards.py
Enter 	w for web, 
	m for mobile, 
	b for both, 
	o for offers, 
	a for all, 
	r for remaining (default) 
Input: 	a

	You selected all

> Starting web search
       >> Logging in
           << Successfully logged in
       >> Starting search
Traceback (most recent call last):
  File "BingRewards.py", line 219, in <module>
    __main(args[0], arg1)
  File "BingRewards.py", line 159, in __main
    rewards.complete_all()
  File "/Users/Stew/Documents/bing-rewards-master/BingRewards/src/driver.py", line 693, in complete_all
    driver = self.__complete_web_search()
  File "/Users/Stew/Documents/bing-rewards-master/BingRewards/src/driver.py", line 597, in __complete_web_search
    self.completion.web_search = self.__search(driver, Driver.WEB_DEVICE)
  File "/Users/Stew/Documents/bing-rewards-master/BingRewards/src/driver.py", line 240, in __search
    current_progress, complete_progress = self.__get_search_progress(driver, device)
  File "/Users/Stew/Documents/bing-rewards-master/BingRewards/src/driver.py", line 194, in __get_search_progress
    progress_elements = WebDriverWait(driver, self.__WEB_DRIVER_WAIT_LONG).until(EC.visibility_of_all_elements_located((By.XPATH, '//*[@id="userPointsBreakdown"]/div/div[*]')))[1:]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by spatel4140** [comment]
Hmm I've seen this before but I am not sure at the moment what could be causing this. I don't believe increasing the wait time is the solution either as it may be due to some web elements not loading on the page. 

Sorry for the inconvenience, I'll keep this in mind.

**Comment by gordon-sk** [comment]
Yeah, let me know if you think you've fixed it and I'll redownload your code and give it a try

**Comment by spatel4140** [comment]
I was able to replicate this issue on a Mac although it appears to happen randomly. Interestingly, if I set headless mode to False it ends up working but that's not something you'd want to do as it ruins the user experience. But this makes me believe the issue is with the chromedriver build and how they are supporting headless mode on Macs. 

No fix yet, just letting you know what might be causing it.
