### ISSUE TITLE
Mobile Search points_url timeout

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#20]
So this happens every time for me at least;

```
2018-06-11T08:37:53.920253454Z > Starting mobile search

2018-06-11T08:37:53.920258013Z        >> Logging in

2018-06-11T08:37:53.920262142Z            << Successfully logged in

2018-06-11T08:37:53.920266314Z        >> Starting search

2018-06-11T08:41:36.845204200Z Traceback (most recent call last):

2018-06-11T08:41:36.845239012Z   File "/app/BingRewards/src/rewards.py", line 104, in __get_search_progress

2018-06-11T08:41:36.845244825Z     driver.get(self.__POINTS_URL)

2018-06-11T08:41:36.845249429Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 78, in get

2018-06-11T08:41:36.845254516Z     self._dispatch("navigate_to", (url, self._driver), "get", (url, ))

2018-06-11T08:41:36.845259349Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 160, in _dispatch

2018-06-11T08:41:36.845264192Z     raise e

2018-06-11T08:41:36.845268613Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 157, in _dispatch

2018-06-11T08:41:36.845273398Z     result = getattr(self._driver, d_call)(*d_args)

2018-06-11T08:41:36.845277903Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 326, in get

2018-06-11T08:41:36.845282586Z     self.execute(Command.GET, {'url': url})

2018-06-11T08:41:36.845287072Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute

2018-06-11T08:41:36.845291780Z     self.error_handler.check_response(response)

2018-06-11T08:41:36.845296253Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response

2018-06-11T08:41:36.845301033Z     raise exception_class(message, screen, stacktrace)

2018-06-11T08:41:36.845305485Z selenium.common.exceptions.TimeoutException: Message: timeout

2018-06-11T08:41:36.845309941Z   (Session info: chrome=67.0.3396.62)

2018-06-11T08:41:36.845314362Z   (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.9.0-6-amd64 x86_64)

2018-06-11T08:41:36.845319011Z 

2018-06-11T08:41:36.845323330Z 

2018-06-11T08:41:36.845327656Z During handling of the above exception, another exception occurred:

2018-06-11T08:41:36.845332124Z 

2018-06-11T08:41:36.845336373Z Traceback (most recent call last):

2018-06-11T08:41:36.845340744Z   File "/app/BingRewards/BingRewards.py", line 139, in <module>

2018-06-11T08:41:36.845345566Z     __main(args[0], arg1.replace("-", ""))

2018-06-11T08:41:36.845350083Z   File "/app/BingRewards/BingRewards.py", line 84, in __main

2018-06-11T08:41:36.845354653Z     rewards.complete_all(hist_log.get_search_hist())

2018-06-11T08:41:36.845359170Z   File "/app/BingRewards/src/rewards.py", line 662, in complete_all

2018-06-11T08:41:36.845369847Z     driver = self.__complete_mobile_search()

2018-06-11T08:41:36.845374347Z   File "/app/BingRewards/src/rewards.py", line 573, in __complete_mobile_search

2018-06-11T08:41:36.845378660Z     self.completion.mobile_search = self.__search(driver, Driver.MOBILE_DEVICE)

2018-06-11T08:41:36.845395981Z   File "/app/BingRewards/src/rewards.py", line 180, in __search

2018-06-11T08:41:36.845404214Z     current_progress, complete_progress = self.__get_search_progress(driver, device)

2018-06-11T08:41:36.845408912Z   File "/app/BingRewards/src/rewards.py", line 106, in __get_search_progress

2018-06-11T08:41:36.845413191Z     driver.refresh()

2018-06-11T08:41:36.845417279Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 192, in _wrap

2018-06-11T08:41:36.845421759Z     result = attrib(*args, **kwargs)

2018-06-11T08:41:36.845425943Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 817, in refresh

2018-06-11T08:41:36.845430330Z     self.execute(Command.REFRESH)

2018-06-11T08:41:36.845434447Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute

2018-06-11T08:41:36.845438838Z     self.error_handler.check_response(response)

2018-06-11T08:41:36.845443013Z   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response

2018-06-11T08:41:36.845447384Z     raise exception_class(message, screen, stacktrace)

2018-06-11T08:41:36.845451512Z selenium.common.exceptions.TimeoutException: Message: timeout

2018-06-11T08:41:36.845455708Z   (Session info: chrome=67.0.3396.62)

2018-06-11T08:41:36.845461573Z   (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.9.0-6-amd64 x86_64)

2018-06-11T08:41:36.845465993Z 

```

**Comment by spatel4140** [comment]
I've been experiencing the same issue, and for some strange reason only with mobile search. It sometimes hangs when trying to load the site. 

Over the next few days I can try monitoring the use of an updated chromedriver, and a new mobile user-agent string to see if that solves the problem. But I was also considering changing the design so that it only checks the progress once in the beginning to determine how many times it needs to search.

**Comment by ShoGinn** [comment]
yeah its weird, since it resolves itself.
