### ISSUE TITLE
Search Error (Newest Commit)

### ISSUE THREAD

**Issue by Brenex** [spatel4140/bing-rewards#5]
DevTools listening on ws://127.0.0.1:12883/devtools/browser/6fd2cd34-98d1-45a1-88fa-2a48224faf48
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Dashboard Type: 2
Traceback (most recent call last):
  File ".\BingRewards.py", line 231, in <module>
    completion = rewards.complete_all()
  File "C:\Users\Danny\Downloads\bing-rewards\BingRewards\src\driver.py", line 614, in complete_all
    self.__complete_web_search()
  File "C:\Users\Danny\Downloads\bing-rewards\BingRewards\src\driver.py", line 539, in __complete_web_search
    self.__completion.web_search = self.__search(web_driver.driver, Driver.WEB_DEVICE)
  File "C:\Users\Danny\Downloads\bing-rewards\BingRewards\src\driver.py", line 255, in __search
    current_progress, complete_progress = self.__get_search_progress(driver, device)
  File "C:\Users\Danny\Downloads\bing-rewards\BingRewards\src\driver.py", line 204, in __get_search_progress
    progress_name = element.find_element_by_xpath('./div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[1]/a').text.lower()
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 263, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 518, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"./div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[1]/a"}
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

**Comment by Brenex** [comment]
fixed in newest version
