### ISSUE TITLE
Quiz Failed

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#8]
So today it decided not to complete the Quiz. Not much extra info in the code on why.

Not that I hope yours doesn't work. I can try and debug it later!

````

	You selected remaining,

> Starting offers,
       >> Logging in,
           << Successfully logged in,
       >> Trying English bulldog,
           << Successfully completed English bulldog,
       >> Trying Turbocharge Quiz,
              >>> Starting quiz,
                     >>>> Already started quiz,
                     >>>> Multiple choice,

                  <<< Failed to complete quiz,
           << Failed to complete Turbocharge Quiz,
       >> Trying Old Man River,
           << Successfully completed Old Man River,
       >> Trying Congratulations!,
           << Already checked,
       >> Trying Love Fortnite?,
           << Already checked,
       >> Trying You're missing out,
           << Already checked,
       >> Trying Supersonic Quiz,
           << Already checked,
       >> Trying Lightspeed Quiz,
           << Already checked,
       >> Trying Warpspeed Quiz,
           << Already checked,
    < Failed to complete offers,

**Comment by spatel4140** [comment]
Sorry about that, I found the bug that may also have been causing previous multiple choice quizzes in the past to fail as well.  

Thanks for pointing this out!

**Comment by ShoGinn** [comment]
gotcha! now its failing in a weird way ;) if you delete the logs for the day and have it "re-attempt"

````

       >> Trying Turbocharge Quiz

              >>> Starting quiz

                  <<< Already started quiz

              >>> Multiple choice

Traceback (most recent call last):

  File "BingRewards.py", line 211, in <module>

    __main(args[0], arg1.replace("-", ""))

  File "BingRewards.py", line 169, in __main

    completion = rewards.complete_offers()

  File "/app/src/driver.py", line 686, in complete_offers

    self.__complete_offers()

  File "/app/src/driver.py", line 658, in __complete_offers

    self.completion.offers = self.__offers(driver.driver)

  File "/app/src/driver.py", line 561, in __offers

    c = self.__click_offer(driver, offer, './div[2]/h3', './mee-rewards-points/div/div/span[2]', './div[2]/p')

  File "/app/src/driver.py", line 534, in __click_offer

    completed = self.__quiz(driver)

  File "/app/src/driver.py", line 469, in __quiz

    EC.element_to_be_clickable((By.ID, "rqAnswerOption{0}".format(option_index)))).click()

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 71, in until

    value = method(self._driver)

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/expected_conditions.py", line 283, in __call__

    element = visibility_of_element_located(self.locator)(driver)

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/expected_conditions.py", line 127, in __call__

    return _element_if_visible(_find_element(driver, self.locator))

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/expected_conditions.py", line 402, in _find_element

    raise e

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/expected_conditions.py", line 398, in _find_element

    return driver.find_element(*by)

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 858, in find_element

    'value': value})['value']

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute

    self.error_handler.check_response(response)

  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response

    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None

Message: unexpected alert open: {Alert text : Want more relevant search results? Allow Bing to access your location. Click 'OK' on the next prompt.}

  (Session info: chrome=64.0.3282.119)

  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.0-6-amd64 x86_64)

**Comment by ShoGinn** [comment]
FYI; my line items are different then yours since I modified it to work with selenium-grid so sorry if thats confusing.

**Comment by spatel4140** [comment]
Thanks and nice find! :)
